### ISSUE TITLE
Neuroimaging Meta-Analyses! (Neurosynth-Compose + NiMARE)

### ISSUE THREAD

**Issue by jdkent** [ohbm/hackathon2023#14]
### Title

Neuroimaging Meta-Analyses! (NiMARE + Neurosynth-Compose)

### Short description and the goals for the OHBM BrainHack

We are on an exciting precipice of making reproducible/sharable neuroimaging meta-analyses more accessible to a broader audience and we want your help to make it a reality.

We have multiple projects you can interface with that fit your level of experience (from newcomer to veteran)

# Novice Projects

## User testing
 Walk through our https://compose.neurosynth.org/ using a [tutorial](https://neurostuff.github.io/meta-analysis-book) 

### Goals
provide feedback on what was intuitive/what didn’t make sense/what didn’t work in the tutorial or on the platform.

# Intermediate Projects

## Coordinate Based Meta-Regression exploration
If you have run a meta-analysis before using kernel-based methods and want to try Coordinate-based meta-regression

### Goals
- Execute a meta-analysis with meta-regression and compare the results to a kernel-based method
- Provide feedback on the usability of the library
- Identify bugs

## Documentation/Educational Material Development
If you have some knowledge of meta-analyses and want to explain concepts and help organize an educational book, we can use contributors to the meta-analysis-book

### Goals
- Create exercises for sections of the book
- Provide more fundamental knowledge about kernel-based methods
- Outline Image-Based Meta-Analysis Section

# Advanced Projects

## Data mining
Use the neurosynth dataset to recreate term meta-analyses using coordinate-based meta-regression. 

### Goals
- Determine the feasibility of using neurosynth dataset with CBMR
- Compare results with original term meta-analyses on neurosynth

## Image-Based Meta-Analysis
Prototype workflow for Image Based Meta-Analysis, and help develop the components to make it possible to run an image-based meta-analysis on compose.neurosynth.org and NiMARE

### Goals
- Create a workflow to complete an Image Based Meta-Analysis

## Support Coordinate Based Meta-Regression on https://compose.neurosynth.org/
Help make a new neuroimaging meta-analytic method accessible to a broader audience

### Goals
- Outline changes to the API
- Outline changes to the meta-analysis runner
- Create a coordinate-based meta-regression workflow on neurosynth-compose

### Link to the Project

https://github.com/neurostuff/NiMARE

### Image for the OHBM brainhack website

https://compose.neurosynth.org/static/synth.png

### Project lead

| Name                 | github    | discord         |
|----------------------|-----------|-----------------|
| James Kent           | jdkent    | jdkent          |
| Alejandro De La Vega | adelavega | neurozorro#2158 |
| Yifan Yu             | yifan0330 | Yifan Yu#0260   |

### Main Hub

Montreal

### Other Hub covered by the leaders

- [ ] Montreal
- [ ] Asia / Pacific
- [ ] Europe / Middle East / Africa
- [ ] Americas

### Skills

Novice Projects:
- None

Intermediate Projects:
- Python (beginner/confirmed)
- meta-analyses (confirmed)
- git: 0/1

Advanced Projects:
- Python (confirmed/advanced)
- meta-analyses (confirmed)
- git: 1/2

### Recommended tutorials for new contributors

- [X] [Set up a brainhack friendly computing environment](https://school-brainhack.github.io/modules/installation/)
- [ ] [A introduction to Bash](https://school-brainhack.github.io/modules/introduction_to_terminal/)
- [X] [Python: Writing a script](https://school-brainhack.github.io/modules/python_scripts/)
- [X] [Python: Data analysis with Python](https://school-brainhack.github.io/modules/python_data_analysis/)
- [ ] [Python: Visualisation](https://school-brainhack.github.io/modules/python_visualization/)
- [ ] [Machine learning basics](https://school-brainhack.github.io/modules/machine_learning_basics/)
- [ ] [BIDS](https://school-brainhack.github.io/modules/bids/)
- [ ] [Machine learning for neuroimaging](https://school-brainhack.github.io/modules/machine_learning_neuroimaging/)
- [X] [VCS: Using Git and Github](https://school-brainhack.github.io/modules/git_github/)
- [X] [VCS: Data management with Datalad](https://school-brainhack.github.io/modules/datalad/)
- [ ] [Virtualization](https://school-brainhack.github.io/modules/containers/)
- [ ] High Performance Computing: [Oracle cloud resource](https://brainhack.org/brainhack_cloud/)

### Twitter summary

Hack with us on neurosynth-compose and NiMARE to create reproducible/sharable neuroimaging meta-analyses!

### Short name for the Discord chat channel (~15 chars)

neurosynth-compose

### Please read and follow the OHBM Code of Conduct

- [X] I agree to follow the OHBM Code of Conduct during the hackathon
